### ISSUE TITLE
var underlyingView

### ISSUE THREAD

**Issue by kmalkic** [ustwo/baseviewcontroller-swift#1]
Like the idea of this base vc!
I spotted an issue in public var underlyingView: T {
I think the return should be true or just raise an exception, because let say i'm overriding loadView with some other view, once I hit viewDidLoad, underlyingView will be called and force allocate a new view of the right type. And I dont think this is allowed to load a new view of a viewController after loadView is called.

**Comment by ghost** [comment]
The reason we don't throw is that we you'd have to use `try` every time you wanted to use `underlyingView`.

Why would you want to swap out the root view of the view controller?

**Comment by kmalkic** [comment]
this is exactly my point Why would you want to swap out the root view of the view controller?
the only time --- if let myView = view as? T --- would be nil is if you overloaded the loadView.
All you would need is --- return view as! T ---

**Comment by ghost** [comment]
The swap was used instead of `return view as! T` in order to prevent a fatal error if the programmer was not using the `BaseViewController` properly and did swap out the view. I try to write frameworks that never cause a crash. More a personal preference of mine as both ways are valid.
